package report

import (
	"fmt"
	"strings"
)

// RenderKnowledgeMap produces docs/knowledge-map.md — Phase 5b's ADDENDUM §B.7 output —
// written into the *code* repo rather than the vault, so a reader who starts from the
// code (not Obsidian) can still find what's written about it. It is the same
// module→notes join as moc/codebase.md, minus the churn and owner columns that belong to
// the weekly pass, not to a file a code reviewer will read next to the source tree.
//
// Groups with no notes are omitted rather than listed as empty: a knowledge map is an
// index of what exists, and CodebaseInput.Uncovered / reports/coverage.md already carry
// the "nothing written here yet" signal for the vault-side audience.
//
// DependsOn is in CodeGroup but nothing in this codebase populates it (see
// cmd/forge/check_codebase.go), so it is omitted here too rather than rendering a column
// that would always read empty.
func RenderKnowledgeMap(groups []CodeGroup) []byte {
	var b strings.Builder
	b.WriteString("# Knowledge map\n\n")
	b.WriteString("Generated by `forge logback` — every module a vault note cites, and " +
		"which notes cite it. Do not edit by hand; rerun `forge logback` instead.\n")
	documented := documentedGroups(groups)
	if len(documented) == 0 {
		b.WriteString("\n_No module in this repository is cited by a vault note yet._\n")
		return []byte(b.String())
	}
	for _, g := range documented {
		writeMapGroup(&b, g)
	}
	return []byte(b.String())
}

func documentedGroups(groups []CodeGroup) []CodeGroup {
	out := make([]CodeGroup, 0, len(groups))
	for _, g := range groups {
		if len(g.Notes) > 0 {
			out = append(out, g)
		}
	}
	return out
}

func writeMapGroup(b *strings.Builder, g CodeGroup) {
	fmt.Fprintf(b, "\n## %s\n\n", g.Name)
	writeGroupNotes(b, g)
}
