package report

import (
	"fmt"
	"strings"
)

// RenderKnowledgeMap produces docs/knowledge-map.md — per docs/ARCHITECTURE.md §10 —
// for the *code* repo rather than the vault, so a reader who starts from the code.
func RenderKnowledgeMap(groups []CodeGroup) []byte {
	var b strings.Builder
	b.WriteString("# Knowledge map\n\n")
	b.WriteString("Generated by `forge logback` — every module a vault note cites, and " +
		"which notes cite it. Do not edit by hand; rerun `forge logback` instead.\n")
	documented := documentedGroups(groups)
	if len(documented) == 0 {
		b.WriteString("\n_No module in this repository is cited by a vault note yet._\n")
		return []byte(b.String())
	}
	for _, g := range documented {
		writeMapGroup(&b, g)
	}
	return []byte(b.String())
}

func documentedGroups(groups []CodeGroup) []CodeGroup {
	out := make([]CodeGroup, 0, len(groups))
	for _, g := range groups {
		if len(g.Notes) > 0 {
			out = append(out, g)
		}
	}
	return out
}

func writeMapGroup(b *strings.Builder, g CodeGroup) {
	fmt.Fprintf(b, "\n## %s\n\n", g.Name)
	writeGroupNotes(b, g)
}
